name: 'Run tailor-log'
description: 'GitHub Action for tailor-log'
branding:
  icon: 'upload-cloud'
  color: 'purple'
inputs:
  tailor-token:
    description: The Tailor Platform token
    default: ''
    required: true
  github-token:
    description: The GitHub token
    default: ${{ github.token }}
    required: false
  datadog-api-key:
    description: The Datadog API key
    default: ''
    required: true
  datadog-site:
    description: The Datadog site
    default: ''
    required: true
  workspace-id:
    description: Workspace ID
    default: ''
    required: true
  datadog-service:
    description: Service name for Datadog
    default: ''
    required: true
  datadog-tags:
    description: Tags for Datadog
    default: ''
    required: true
  inputs:
    description: Inputs
    default: '*'
    required: false
runs:
  using: 'composite'
  steps:
    -
      uses: k1LoW/gh-setup@0f243b18b55c459d1a125e275884413e4bbaef0a # v1.11.6
      with:
        repo: github.com/k1LoW/tailor-log
        github-token: ${{ inputs.github-token }}
        strict: true
    -
      name: Run tailor-log
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
      with:
        script: |
          const path = require('path');
          const inputs = ${{ toJSON(inputs) }};
          const toolpath = await io.which('tailor-log', true);
          const opt = ['--workspace-id', inputs['workspace-id'], '--datadog-service', inputs['datadog-service'], '--datadog-tag', inputs['datadog-tags'], '--input', inputs['inputs'], '--pos', 'artifact'];
          const options = {};
          await exec.exec(`${toolpath} ingest`, opt, options);
      env:
        TAILOR_TOKEN: ${{ inputs.tailor-token }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
        DD_API_KEY: ${{ inputs.datadog-api-key }}
        DD_SITE: ${{ inputs.datadog-site }}
