name: 'Run tailor-log'
description: 'GitHub Action for tailor-log'
branding:
  icon: 'upload-cloud'
  color: 'purple'
inputs:
  tailor-token:
    description: The Tailor Platform token
    default: ''
    required: true
  github-token:
    description: The GitHub token
    default: ${{ github.token }}
    required: false
  datadog-api-key:
    description: The Datadog API key
    default: ''
    required: true
  datadog-site:
    description: The Datadog site
    default: ''
    required: true
  workspace-id:
    description: Workspace ID
    default: ''
    required: true
  datadog-service:
    description: Service name for Datadog
    default: ''
    required: true
  datadog-tags:
    description: Tags for Datadog
    default: ''
    required: false
runs:
  using: 'composite'
  steps:
    -
      uses: k1LoW/gh-setup@cfadd455483f37fbb46ca1b3b63532cb62927cb3 # v1.11.3
      with:
        repo: github.com/k1LoW/tailor-log
        github-token: ${{ inputs.github-token }}
        strict: true
    -
      name: Run tailor-log
      run: |
        tailor-log ingest --workspace-id ${{inputs.workspace-id}} \
        --datadog-service ${{inputs.datadog-service}} \
        --datadog-tag ${{inputs.datadog-tags}} \
        --pos artifact
      shell: bash
      env:
        TAILOR_TOKEN: ${{ inputs.tailor-token }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
        DD_API_KEY: ${{ inputs.datadog-api-token }}
        DD_SITE: ${{ inputs.datadog-site }}
